#!/bin/bash

#$1 artic directory
artic_dir=$1

#load conda
source ~/miniconda3/etc/profile.d/conda.sh

#nextcladae
~/0_scripts/nextclade ${artic_dir}/consensus.fasta

#metrics
conda activate artic-ncov2019
~/0_scripts/metrics ${artic_dir} ${artic_dir}/metrics.csv

#pangolin
conda activate pangolin
pangolin --update
pangolin consensus.fasta

#reporte
python ~/0_scripts/make_report.py ${artic_dir}/lineage_report.csv ${artic_dir}/nextclade_output/nextclade.csv ${artic_dir}/metrics.csv ${artic_dir}/metadatos.csv

conda deactivate
conda deactivate
