#!/bin/bash

# [1] path a multifasta de entrada
echo "Running Nextclade Analysis for: ${1}"

/home/ins/1_programas/nextclade_v1/nextclade \
 --input-fasta=$1 \
 --input-root-seq=/home/ins/1_programas/nextclade_v1/reference.fasta \
 --genes=E,M,N,ORF1a,ORF1b,ORF3a,ORF6,ORF7a,ORF7b,ORF8,ORF9b,S \
 --input-gene-map=/home/ins/1_programas/nextclade_v1/genemap.gff \
 --input-tree=/home/ins/1_programas/nextclade_v1/tree.json \
 --input-qc-config=/home/ins/1_programas/nextclade_v1/qc.json \
 --input-pcr-primers=/home/ins/1_programas/nextclade_v1/primers.csv \
 --output-json=nextclade_output/nextclade.json \
 --output-csv=nextclade_output/nextclade.csv \
 --output-tree=nextclade_output/nextclade.auspice.json \
 --output-dir=nextclade_output/ \
 --output-basename=nextclade \
 --verbosity="error"

echo "Done"
